version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "9002:9002"
    environment:
      WAIT_HOSTS: postgres:5432
      NODE_ENV: development
      PG_HOST: postgres
      PG_USER: root
      PG_PASS: root
      PG_DB: todos
    command: 'sh -c "/wait && npx nodemon -w src -w openapi.yaml -w static src/index.ts"'
    volumes:
      - ./src:/app/src
      - ./openapi.yaml:/app/openapi.yaml
      - ./static:/app/static
    links:
      - postgres
